# The following redirect is intended for use with most SPAs that handle
# routing internally.
  [[redirects]]
  from = "videos/*"
  to = "https://www.fincomun.com.mx/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "https://ephemeral-torte-31ffe2.netlify.app/"
    [headers.values]
    Access-Control-Allow-Origin = "*"